name: enough_serialization
description: Runtime solution for serializing to and deserializing from JSON.  enough_serialization also supports non-generic lists, enums and complex nested objects.
version: 1.3.0
homepage: https://www.github.com/enough-software/enough_serialization

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
